site_name: setuptools scm

nav:
  - index.md
  - usage.md
  - customizing.md
  - config.md
  - integrations.md
  - extending.md
  - overrides.md
  - integrators.md
  - changelog.md
theme:
  name: material

watch:
- setuptools-scm/src/setuptools_scm
- vcs-versioning/src/vcs_versioning
- docs
markdown_extensions:
  - def_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences

plugins:
- entangled
- search
- include-markdown
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [ setuptools-scm/src, vcs-versioning/src ]
        import:
          - https://docs.python.org/3/objects.inv
        options:
          separate_signature: true
          show_signature_annotations: true
          allow_inspection: true
          show_root_heading: true
          extensions:
            - griffe_public_wildcard_imports
